#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalashDynamics.Web.EMR
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PalashDynamics")]
	public partial class DataDrivenModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEMRTemplate(EMRTemplate instance);
    partial void UpdateEMRTemplate(EMRTemplate instance);
    partial void DeleteEMRTemplate(EMRTemplate instance);
    partial void InsertVariance(Variance instance);
    partial void UpdateVariance(Variance instance);
    partial void DeleteVariance(Variance instance);
    partial void InsertPatientEMRData(PatientEMRData instance);
    partial void UpdatePatientEMRData(PatientEMRData instance);
    partial void DeletePatientEMRData(PatientEMRData instance);
    #endregion
		
		public DataDrivenModelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PalashDynamicsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDrivenModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDrivenModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDrivenModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDrivenModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EMRTemplate> EMRTemplates
		{
			get
			{
				return this.GetTable<EMRTemplate>();
			}
		}
		
		public System.Data.Linq.Table<IntraTemplateRelation> IntraTemplateRelations
		{
			get
			{
				return this.GetTable<IntraTemplateRelation>();
			}
		}
		
		public System.Data.Linq.Table<Variance> Variances
		{
			get
			{
				return this.GetTable<Variance>();
			}
		}
		
		public System.Data.Linq.Table<PatientEMRData> PatientEMRDatas
		{
			get
			{
				return this.GetTable<PatientEMRData>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTemplateDetailsByTemplateId")]
		public ISingleResult<GetTemplateDetailsByTemplateIdResult> GetTemplateDetailsByTemplateId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TemplateId", DbType="BigInt")] System.Nullable<long> templateId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), templateId);
			return ((ISingleResult<GetTemplateDetailsByTemplateIdResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EMRTemplate")]
	public partial class EMRTemplate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _TemplateId;
		
		private string _Title;
		
		private string _Description;
		
		private string _Template;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTemplateIdChanging(long value);
    partial void OnTemplateIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnTemplateChanging(string value);
    partial void OnTemplateChanged();
    #endregion
		
		public EMRTemplate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long TemplateId
		{
			get
			{
				return this._TemplateId;
			}
			set
			{
				if ((this._TemplateId != value))
				{
					this.OnTemplateIdChanging(value);
					this.SendPropertyChanging();
					this._TemplateId = value;
					this.SendPropertyChanged("TemplateId");
					this.OnTemplateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(20)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(250)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Template", DbType="NVarChar(MAX)")]
		public string Template
		{
			get
			{
				return this._Template;
			}
			set
			{
				if ((this._Template != value))
				{
					this.OnTemplateChanging(value);
					this.SendPropertyChanging();
					this._Template = value;
					this.SendPropertyChanged("Template");
					this.OnTemplateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IntraTemplateRelations")]
	public partial class IntraTemplateRelation
	{
		
		private long _RelationId;
		
		private long _TemplateId;
		
		private string _SourceSectionId;
		
		private string _SourceFieldId;
		
		private string _TargetSectionId;
		
		private string _TargetFieldId;
		
		private string _Condition;
		
		public IntraTemplateRelation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelationId", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long RelationId
		{
			get
			{
				return this._RelationId;
			}
			set
			{
				if ((this._RelationId != value))
				{
					this._RelationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateId", DbType="BigInt NOT NULL")]
		public long TemplateId
		{
			get
			{
				return this._TemplateId;
			}
			set
			{
				if ((this._TemplateId != value))
				{
					this._TemplateId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceSectionId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SourceSectionId
		{
			get
			{
				return this._SourceSectionId;
			}
			set
			{
				if ((this._SourceSectionId != value))
				{
					this._SourceSectionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceFieldId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SourceFieldId
		{
			get
			{
				return this._SourceFieldId;
			}
			set
			{
				if ((this._SourceFieldId != value))
				{
					this._SourceFieldId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetSectionId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TargetSectionId
		{
			get
			{
				return this._TargetSectionId;
			}
			set
			{
				if ((this._TargetSectionId != value))
				{
					this._TargetSectionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TargetFieldId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TargetFieldId
		{
			get
			{
				return this._TargetFieldId;
			}
			set
			{
				if ((this._TargetFieldId != value))
				{
					this._TargetFieldId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Condition", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Condition
		{
			get
			{
				return this._Condition;
			}
			set
			{
				if ((this._Condition != value))
				{
					this._Condition = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Variance")]
	public partial class Variance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _VarianceId;
		
		private long _DoctorId;
		
		private long _ClinicId;
		
		private long _PatientId;
		
		private System.DateTime _Date;
		
		private System.Nullable<long> _VisitId;
		
		private string _Variance1;
		
		private string _Variance2;
		
		private string _Variance3;
		
		private string _Variance4;
		
		private string _Variance5;
		
		private string _Variance6;
		
		private string _Variance7;
		
		private string _ListVariance1;
		
		private string _ListVariance2;
		
		private string _ListVariance3;
		
		private string _ListVariance4;
		
		private string _ListVariance5;
		
		private string _ListVariance6;
		
		private string _ListVariance7;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVarianceIdChanging(long value);
    partial void OnVarianceIdChanged();
    partial void OnDoctorIdChanging(long value);
    partial void OnDoctorIdChanged();
    partial void OnClinicIdChanging(long value);
    partial void OnClinicIdChanged();
    partial void OnPatientIdChanging(long value);
    partial void OnPatientIdChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnVisitIdChanging(System.Nullable<long> value);
    partial void OnVisitIdChanged();
    partial void OnVariance1Changing(string value);
    partial void OnVariance1Changed();
    partial void OnVariance2Changing(string value);
    partial void OnVariance2Changed();
    partial void OnVariance3Changing(string value);
    partial void OnVariance3Changed();
    partial void OnVariance4Changing(string value);
    partial void OnVariance4Changed();
    partial void OnVariance5Changing(string value);
    partial void OnVariance5Changed();
    partial void OnVariance6Changing(string value);
    partial void OnVariance6Changed();
    partial void OnVariance7Changing(string value);
    partial void OnVariance7Changed();
    partial void OnListVariance1Changing(string value);
    partial void OnListVariance1Changed();
    partial void OnListVariance2Changing(string value);
    partial void OnListVariance2Changed();
    partial void OnListVariance3Changing(string value);
    partial void OnListVariance3Changed();
    partial void OnListVariance4Changing(string value);
    partial void OnListVariance4Changed();
    partial void OnListVariance5Changing(string value);
    partial void OnListVariance5Changed();
    partial void OnListVariance6Changing(string value);
    partial void OnListVariance6Changed();
    partial void OnListVariance7Changing(string value);
    partial void OnListVariance7Changed();
    #endregion
		
		public Variance()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VarianceId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long VarianceId
		{
			get
			{
				return this._VarianceId;
			}
			set
			{
				if ((this._VarianceId != value))
				{
					this.OnVarianceIdChanging(value);
					this.SendPropertyChanging();
					this._VarianceId = value;
					this.SendPropertyChanged("VarianceId");
					this.OnVarianceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoctorId", DbType="BigInt NOT NULL")]
		public long DoctorId
		{
			get
			{
				return this._DoctorId;
			}
			set
			{
				if ((this._DoctorId != value))
				{
					this.OnDoctorIdChanging(value);
					this.SendPropertyChanging();
					this._DoctorId = value;
					this.SendPropertyChanged("DoctorId");
					this.OnDoctorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClinicId", DbType="BigInt NOT NULL")]
		public long ClinicId
		{
			get
			{
				return this._ClinicId;
			}
			set
			{
				if ((this._ClinicId != value))
				{
					this.OnClinicIdChanging(value);
					this.SendPropertyChanging();
					this._ClinicId = value;
					this.SendPropertyChanged("ClinicId");
					this.OnClinicIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientId", DbType="BigInt NOT NULL")]
		public long PatientId
		{
			get
			{
				return this._PatientId;
			}
			set
			{
				if ((this._PatientId != value))
				{
					this.OnPatientIdChanging(value);
					this.SendPropertyChanging();
					this._PatientId = value;
					this.SendPropertyChanged("PatientId");
					this.OnPatientIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitId", DbType="BigInt")]
		public System.Nullable<long> VisitId
		{
			get
			{
				return this._VisitId;
			}
			set
			{
				if ((this._VisitId != value))
				{
					this.OnVisitIdChanging(value);
					this.SendPropertyChanging();
					this._VisitId = value;
					this.SendPropertyChanged("VisitId");
					this.OnVisitIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variance1", DbType="NVarChar(100)")]
		public string Variance1
		{
			get
			{
				return this._Variance1;
			}
			set
			{
				if ((this._Variance1 != value))
				{
					this.OnVariance1Changing(value);
					this.SendPropertyChanging();
					this._Variance1 = value;
					this.SendPropertyChanged("Variance1");
					this.OnVariance1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variance2", DbType="NVarChar(100)")]
		public string Variance2
		{
			get
			{
				return this._Variance2;
			}
			set
			{
				if ((this._Variance2 != value))
				{
					this.OnVariance2Changing(value);
					this.SendPropertyChanging();
					this._Variance2 = value;
					this.SendPropertyChanged("Variance2");
					this.OnVariance2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variance3", DbType="NVarChar(100)")]
		public string Variance3
		{
			get
			{
				return this._Variance3;
			}
			set
			{
				if ((this._Variance3 != value))
				{
					this.OnVariance3Changing(value);
					this.SendPropertyChanging();
					this._Variance3 = value;
					this.SendPropertyChanged("Variance3");
					this.OnVariance3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variance4", DbType="NVarChar(100)")]
		public string Variance4
		{
			get
			{
				return this._Variance4;
			}
			set
			{
				if ((this._Variance4 != value))
				{
					this.OnVariance4Changing(value);
					this.SendPropertyChanging();
					this._Variance4 = value;
					this.SendPropertyChanged("Variance4");
					this.OnVariance4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variance5", DbType="NVarChar(100)")]
		public string Variance5
		{
			get
			{
				return this._Variance5;
			}
			set
			{
				if ((this._Variance5 != value))
				{
					this.OnVariance5Changing(value);
					this.SendPropertyChanging();
					this._Variance5 = value;
					this.SendPropertyChanged("Variance5");
					this.OnVariance5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variance6", DbType="NVarChar(100)")]
		public string Variance6
		{
			get
			{
				return this._Variance6;
			}
			set
			{
				if ((this._Variance6 != value))
				{
					this.OnVariance6Changing(value);
					this.SendPropertyChanging();
					this._Variance6 = value;
					this.SendPropertyChanged("Variance6");
					this.OnVariance6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variance7", DbType="NVarChar(100)")]
		public string Variance7
		{
			get
			{
				return this._Variance7;
			}
			set
			{
				if ((this._Variance7 != value))
				{
					this.OnVariance7Changing(value);
					this.SendPropertyChanging();
					this._Variance7 = value;
					this.SendPropertyChanged("Variance7");
					this.OnVariance7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListVariance1", DbType="NVarChar(MAX)")]
		public string ListVariance1
		{
			get
			{
				return this._ListVariance1;
			}
			set
			{
				if ((this._ListVariance1 != value))
				{
					this.OnListVariance1Changing(value);
					this.SendPropertyChanging();
					this._ListVariance1 = value;
					this.SendPropertyChanged("ListVariance1");
					this.OnListVariance1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListVariance2", DbType="NVarChar(MAX)")]
		public string ListVariance2
		{
			get
			{
				return this._ListVariance2;
			}
			set
			{
				if ((this._ListVariance2 != value))
				{
					this.OnListVariance2Changing(value);
					this.SendPropertyChanging();
					this._ListVariance2 = value;
					this.SendPropertyChanged("ListVariance2");
					this.OnListVariance2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListVariance3", DbType="NVarChar(MAX)")]
		public string ListVariance3
		{
			get
			{
				return this._ListVariance3;
			}
			set
			{
				if ((this._ListVariance3 != value))
				{
					this.OnListVariance3Changing(value);
					this.SendPropertyChanging();
					this._ListVariance3 = value;
					this.SendPropertyChanged("ListVariance3");
					this.OnListVariance3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListVariance4", DbType="NVarChar(MAX)")]
		public string ListVariance4
		{
			get
			{
				return this._ListVariance4;
			}
			set
			{
				if ((this._ListVariance4 != value))
				{
					this.OnListVariance4Changing(value);
					this.SendPropertyChanging();
					this._ListVariance4 = value;
					this.SendPropertyChanged("ListVariance4");
					this.OnListVariance4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListVariance5", DbType="NVarChar(MAX)")]
		public string ListVariance5
		{
			get
			{
				return this._ListVariance5;
			}
			set
			{
				if ((this._ListVariance5 != value))
				{
					this.OnListVariance5Changing(value);
					this.SendPropertyChanging();
					this._ListVariance5 = value;
					this.SendPropertyChanged("ListVariance5");
					this.OnListVariance5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListVariance6", DbType="NVarChar(MAX)")]
		public string ListVariance6
		{
			get
			{
				return this._ListVariance6;
			}
			set
			{
				if ((this._ListVariance6 != value))
				{
					this.OnListVariance6Changing(value);
					this.SendPropertyChanging();
					this._ListVariance6 = value;
					this.SendPropertyChanged("ListVariance6");
					this.OnListVariance6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListVariance7", DbType="NVarChar(MAX)")]
		public string ListVariance7
		{
			get
			{
				return this._ListVariance7;
			}
			set
			{
				if ((this._ListVariance7 != value))
				{
					this.OnListVariance7Changing(value);
					this.SendPropertyChanging();
					this._ListVariance7 = value;
					this.SendPropertyChanged("ListVariance7");
					this.OnListVariance7Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PatientEMRData")]
	public partial class PatientEMRData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private long _PatientId;
		
		private long _TemplateId;
		
		private string _Template;
		
		private System.Nullable<long> _VisitId;
		
		private string _SavedBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnPatientIdChanging(long value);
    partial void OnPatientIdChanged();
    partial void OnTemplateIdChanging(long value);
    partial void OnTemplateIdChanged();
    partial void OnTemplateChanging(string value);
    partial void OnTemplateChanged();
    partial void OnVisitIdChanging(System.Nullable<long> value);
    partial void OnVisitIdChanged();
    partial void OnSavedByChanging(string value);
    partial void OnSavedByChanged();
    #endregion
		
		public PatientEMRData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientId", DbType="BigInt NOT NULL")]
		public long PatientId
		{
			get
			{
				return this._PatientId;
			}
			set
			{
				if ((this._PatientId != value))
				{
					this.OnPatientIdChanging(value);
					this.SendPropertyChanging();
					this._PatientId = value;
					this.SendPropertyChanged("PatientId");
					this.OnPatientIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateId", DbType="BigInt NOT NULL")]
		public long TemplateId
		{
			get
			{
				return this._TemplateId;
			}
			set
			{
				if ((this._TemplateId != value))
				{
					this.OnTemplateIdChanging(value);
					this.SendPropertyChanging();
					this._TemplateId = value;
					this.SendPropertyChanged("TemplateId");
					this.OnTemplateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Template", DbType="NVarChar(MAX)")]
		public string Template
		{
			get
			{
				return this._Template;
			}
			set
			{
				if ((this._Template != value))
				{
					this.OnTemplateChanging(value);
					this.SendPropertyChanging();
					this._Template = value;
					this.SendPropertyChanged("Template");
					this.OnTemplateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitId", DbType="BigInt")]
		public System.Nullable<long> VisitId
		{
			get
			{
				return this._VisitId;
			}
			set
			{
				if ((this._VisitId != value))
				{
					this.OnVisitIdChanging(value);
					this.SendPropertyChanging();
					this._VisitId = value;
					this.SendPropertyChanged("VisitId");
					this.OnVisitIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SavedBy", DbType="NVarChar(50)")]
		public string SavedBy
		{
			get
			{
				return this._SavedBy;
			}
			set
			{
				if ((this._SavedBy != value))
				{
					this.OnSavedByChanging(value);
					this.SendPropertyChanging();
					this._SavedBy = value;
					this.SendPropertyChanged("SavedBy");
					this.OnSavedByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetTemplateDetailsByTemplateIdResult
	{
		
		private string _XML_F52E2B61_18A1_11d1_B105_00805F49916B;
		
		public GetTemplateDetailsByTemplateIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[XML_F52E2B61-18A1-11d1-B105-00805F49916B]", Storage="_XML_F52E2B61_18A1_11d1_B105_00805F49916B", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string XML_F52E2B61_18A1_11d1_B105_00805F49916B
		{
			get
			{
				return this._XML_F52E2B61_18A1_11d1_B105_00805F49916B;
			}
			set
			{
				if ((this._XML_F52E2B61_18A1_11d1_B105_00805F49916B != value))
				{
					this._XML_F52E2B61_18A1_11d1_B105_00805F49916B = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
