//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public DefaultValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EMR.DefaultValues", typeof(DefaultValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 108.
        /// </summary>
        public static string ClinicalHistoryTemplateID {
            get {
                return ResourceManager.GetString("ClinicalHistoryTemplateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the window ?.
        /// </summary>
        public static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        public static string EMRIconsHeight {
            get {
                return ResourceManager.GetString("EMRIconsHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string EMRMenuParentID {
            get {
                return ResourceManager.GetString("EMRMenuParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 111.
        /// </summary>
        public static string ERPTemplateID {
            get {
                return ResourceManager.GetString("ERPTemplateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while processing the record..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 107.
        /// </summary>
        public static string FamilyHistoryTemplateID {
            get {
                return ResourceManager.GetString("FamilyHistoryTemplateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distolic BP Above Maximum Value .
        /// </summary>
        public static string HighDiastolicBP_Msg {
            get {
                return ResourceManager.GetString("HighDiastolicBP_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O2 Above Maximum Value .
        /// </summary>
        public static string HighO2_Msg {
            get {
                return ResourceManager.GetString("HighO2_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Above Maximum Value .
        /// </summary>
        public static string HighPulseRate_Msg {
            get {
                return ResourceManager.GetString("HighPulseRate_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respiratory Rate Above Maximum Value .
        /// </summary>
        public static string HighRR_Msg {
            get {
                return ResourceManager.GetString("HighRR_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systolic BP Above Maximum Value .
        /// </summary>
        public static string HighSystolicBP_Msg {
            get {
                return ResourceManager.GetString("HighSystolicBP_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Above Maximum Value .
        /// </summary>
        public static string HighTemp_Msg {
            get {
                return ResourceManager.GetString("HighTemp_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Above Maximum Value .
        /// </summary>
        public static string HighWeight_Msg {
            get {
                return ResourceManager.GetString("HighWeight_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diastolic BP Below Min Value .
        /// </summary>
        public static string LowDiastolicBP_Msg {
            get {
                return ResourceManager.GetString("LowDiastolicBP_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O2 Below Minimum Value .
        /// </summary>
        public static string LowO2_Msg {
            get {
                return ResourceManager.GetString("LowO2_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Below Minimum Value .
        /// </summary>
        public static string LowPulseRate_Msg {
            get {
                return ResourceManager.GetString("LowPulseRate_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respiratory Rate Below Minimum Value .
        /// </summary>
        public static string LowRR_Msg {
            get {
                return ResourceManager.GetString("LowRR_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systolic BP Below Minimum Value .
        /// </summary>
        public static string LowSystolicBP_Msg {
            get {
                return ResourceManager.GetString("LowSystolicBP_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Below Minimum Value .
        /// </summary>
        public static string LowTemp_Msg {
            get {
                return ResourceManager.GetString("LowTemp_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Below Maximum Value.
        /// </summary>
        public static string LowWeight_Msg {
            get {
                return ResourceManager.GetString("LowWeight_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 109.
        /// </summary>
        public static string PastHistoryTemplateID {
            get {
                return ResourceManager.GetString("PastHistoryTemplateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 110.
        /// </summary>
        public static string PersonalHistoryTemplateID {
            get {
                return ResourceManager.GetString("PersonalHistoryTemplateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Saved Successfully..
        /// </summary>
        public static string RecordSavePrompt {
            get {
                return ResourceManager.GetString("RecordSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure , You want to save record ?.
        /// </summary>
        public static string SaveConfirmationMsg {
            get {
                return ResourceManager.GetString("SaveConfirmationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save Personal History?.
        /// </summary>
        public static string SavePersonalHist_Msg {
            get {
                return ResourceManager.GetString("SavePersonalHist_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template not found..
        /// </summary>
        public static string TemplateNotFound {
            get {
                return ResourceManager.GetString("TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Vitals !.
        /// </summary>
        public static string VitalEmpty_Msg {
            get {
                return ResourceManager.GetString("VitalEmpty_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 103.
        /// </summary>
        public static string VitalTemplateID {
            get {
                return ResourceManager.GetString("VitalTemplateID", resourceCulture);
            }
        }
    }
}
