//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace PalashDynamics.Service.UserInforServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserInforServiceRef.UserInformationSoap")]
    public interface UserInformationSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetClientUserName", ReplyAction="*")]
        System.IAsyncResult BeginGetClientUserName(PalashDynamics.Service.UserInforServiceRef.GetClientUserNameRequest request, System.AsyncCallback callback, object asyncState);
        
        PalashDynamics.Service.UserInforServiceRef.GetClientUserNameResponse EndGetClientUserName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetClientMachineName", ReplyAction="*")]
        System.IAsyncResult BeginGetClientMachineName(PalashDynamics.Service.UserInforServiceRef.GetClientMachineNameRequest request, System.AsyncCallback callback, object asyncState);
        
        PalashDynamics.Service.UserInforServiceRef.GetClientMachineNameResponse EndGetClientMachineName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetCoordinates", ReplyAction="*")]
        System.IAsyncResult BeginGetCoordinates(PalashDynamics.Service.UserInforServiceRef.GetCoordinatesRequest request, System.AsyncCallback callback, object asyncState);
        
        PalashDynamics.Service.UserInforServiceRef.GetCoordinatesResponse EndGetCoordinates(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClientUserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClientUserName", Namespace="http://tempuri.org/", Order=0)]
        public PalashDynamics.Service.UserInforServiceRef.GetClientUserNameRequestBody Body;
        
        public GetClientUserNameRequest() {
        }
        
        public GetClientUserNameRequest(PalashDynamics.Service.UserInforServiceRef.GetClientUserNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetClientUserNameRequestBody {
        
        public GetClientUserNameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClientUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClientUserNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public PalashDynamics.Service.UserInforServiceRef.GetClientUserNameResponseBody Body;
        
        public GetClientUserNameResponse() {
        }
        
        public GetClientUserNameResponse(PalashDynamics.Service.UserInforServiceRef.GetClientUserNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetClientUserNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetClientUserNameResult;
        
        public GetClientUserNameResponseBody() {
        }
        
        public GetClientUserNameResponseBody(string GetClientUserNameResult) {
            this.GetClientUserNameResult = GetClientUserNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClientMachineNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClientMachineName", Namespace="http://tempuri.org/", Order=0)]
        public PalashDynamics.Service.UserInforServiceRef.GetClientMachineNameRequestBody Body;
        
        public GetClientMachineNameRequest() {
        }
        
        public GetClientMachineNameRequest(PalashDynamics.Service.UserInforServiceRef.GetClientMachineNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetClientMachineNameRequestBody {
        
        public GetClientMachineNameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClientMachineNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClientMachineNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public PalashDynamics.Service.UserInforServiceRef.GetClientMachineNameResponseBody Body;
        
        public GetClientMachineNameResponse() {
        }
        
        public GetClientMachineNameResponse(PalashDynamics.Service.UserInforServiceRef.GetClientMachineNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetClientMachineNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetClientMachineNameResult;
        
        public GetClientMachineNameResponseBody() {
        }
        
        public GetClientMachineNameResponseBody(string GetClientMachineNameResult) {
            this.GetClientMachineNameResult = GetClientMachineNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCoordinatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCoordinates", Namespace="http://tempuri.org/", Order=0)]
        public PalashDynamics.Service.UserInforServiceRef.GetCoordinatesRequestBody Body;
        
        public GetCoordinatesRequest() {
        }
        
        public GetCoordinatesRequest(PalashDynamics.Service.UserInforServiceRef.GetCoordinatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCoordinatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strAddress;
        
        public GetCoordinatesRequestBody() {
        }
        
        public GetCoordinatesRequestBody(string strAddress) {
            this.strAddress = strAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCoordinatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCoordinatesResponse", Namespace="http://tempuri.org/", Order=0)]
        public PalashDynamics.Service.UserInforServiceRef.GetCoordinatesResponseBody Body;
        
        public GetCoordinatesResponse() {
        }
        
        public GetCoordinatesResponse(PalashDynamics.Service.UserInforServiceRef.GetCoordinatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCoordinatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCoordinatesResult;
        
        public GetCoordinatesResponseBody() {
        }
        
        public GetCoordinatesResponseBody(string GetCoordinatesResult) {
            this.GetCoordinatesResult = GetCoordinatesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserInformationSoapChannel : PalashDynamics.Service.UserInforServiceRef.UserInformationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetClientUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetClientUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetClientMachineNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetClientMachineNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCoordinatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCoordinatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserInformationSoapClient : System.ServiceModel.ClientBase<PalashDynamics.Service.UserInforServiceRef.UserInformationSoap>, PalashDynamics.Service.UserInforServiceRef.UserInformationSoap {
        
        private BeginOperationDelegate onBeginGetClientUserNameDelegate;
        
        private EndOperationDelegate onEndGetClientUserNameDelegate;
        
        private System.Threading.SendOrPostCallback onGetClientUserNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetClientMachineNameDelegate;
        
        private EndOperationDelegate onEndGetClientMachineNameDelegate;
        
        private System.Threading.SendOrPostCallback onGetClientMachineNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCoordinatesDelegate;
        
        private EndOperationDelegate onEndGetCoordinatesDelegate;
        
        private System.Threading.SendOrPostCallback onGetCoordinatesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public UserInformationSoapClient() {
        }
        
        public UserInformationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserInformationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserInformationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserInformationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetClientUserNameCompletedEventArgs> GetClientUserNameCompleted;
        
        public event System.EventHandler<GetClientMachineNameCompletedEventArgs> GetClientMachineNameCompleted;
        
        public event System.EventHandler<GetCoordinatesCompletedEventArgs> GetCoordinatesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PalashDynamics.Service.UserInforServiceRef.UserInformationSoap.BeginGetClientUserName(PalashDynamics.Service.UserInforServiceRef.GetClientUserNameRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetClientUserName(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetClientUserName(System.AsyncCallback callback, object asyncState) {
            PalashDynamics.Service.UserInforServiceRef.GetClientUserNameRequest inValue = new PalashDynamics.Service.UserInforServiceRef.GetClientUserNameRequest();
            inValue.Body = new PalashDynamics.Service.UserInforServiceRef.GetClientUserNameRequestBody();
            return ((PalashDynamics.Service.UserInforServiceRef.UserInformationSoap)(this)).BeginGetClientUserName(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PalashDynamics.Service.UserInforServiceRef.GetClientUserNameResponse PalashDynamics.Service.UserInforServiceRef.UserInformationSoap.EndGetClientUserName(System.IAsyncResult result) {
            return base.Channel.EndGetClientUserName(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetClientUserName(System.IAsyncResult result) {
            PalashDynamics.Service.UserInforServiceRef.GetClientUserNameResponse retVal = ((PalashDynamics.Service.UserInforServiceRef.UserInformationSoap)(this)).EndGetClientUserName(result);
            return retVal.Body.GetClientUserNameResult;
        }
        
        private System.IAsyncResult OnBeginGetClientUserName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetClientUserName(callback, asyncState);
        }
        
        private object[] OnEndGetClientUserName(System.IAsyncResult result) {
            string retVal = this.EndGetClientUserName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetClientUserNameCompleted(object state) {
            if ((this.GetClientUserNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetClientUserNameCompleted(this, new GetClientUserNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetClientUserNameAsync() {
            this.GetClientUserNameAsync(null);
        }
        
        public void GetClientUserNameAsync(object userState) {
            if ((this.onBeginGetClientUserNameDelegate == null)) {
                this.onBeginGetClientUserNameDelegate = new BeginOperationDelegate(this.OnBeginGetClientUserName);
            }
            if ((this.onEndGetClientUserNameDelegate == null)) {
                this.onEndGetClientUserNameDelegate = new EndOperationDelegate(this.OnEndGetClientUserName);
            }
            if ((this.onGetClientUserNameCompletedDelegate == null)) {
                this.onGetClientUserNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetClientUserNameCompleted);
            }
            base.InvokeAsync(this.onBeginGetClientUserNameDelegate, null, this.onEndGetClientUserNameDelegate, this.onGetClientUserNameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PalashDynamics.Service.UserInforServiceRef.UserInformationSoap.BeginGetClientMachineName(PalashDynamics.Service.UserInforServiceRef.GetClientMachineNameRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetClientMachineName(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetClientMachineName(System.AsyncCallback callback, object asyncState) {
            PalashDynamics.Service.UserInforServiceRef.GetClientMachineNameRequest inValue = new PalashDynamics.Service.UserInforServiceRef.GetClientMachineNameRequest();
            inValue.Body = new PalashDynamics.Service.UserInforServiceRef.GetClientMachineNameRequestBody();
            return ((PalashDynamics.Service.UserInforServiceRef.UserInformationSoap)(this)).BeginGetClientMachineName(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PalashDynamics.Service.UserInforServiceRef.GetClientMachineNameResponse PalashDynamics.Service.UserInforServiceRef.UserInformationSoap.EndGetClientMachineName(System.IAsyncResult result) {
            return base.Channel.EndGetClientMachineName(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetClientMachineName(System.IAsyncResult result) {
            PalashDynamics.Service.UserInforServiceRef.GetClientMachineNameResponse retVal = ((PalashDynamics.Service.UserInforServiceRef.UserInformationSoap)(this)).EndGetClientMachineName(result);
            return retVal.Body.GetClientMachineNameResult;
        }
        
        private System.IAsyncResult OnBeginGetClientMachineName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetClientMachineName(callback, asyncState);
        }
        
        private object[] OnEndGetClientMachineName(System.IAsyncResult result) {
            string retVal = this.EndGetClientMachineName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetClientMachineNameCompleted(object state) {
            if ((this.GetClientMachineNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetClientMachineNameCompleted(this, new GetClientMachineNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetClientMachineNameAsync() {
            this.GetClientMachineNameAsync(null);
        }
        
        public void GetClientMachineNameAsync(object userState) {
            if ((this.onBeginGetClientMachineNameDelegate == null)) {
                this.onBeginGetClientMachineNameDelegate = new BeginOperationDelegate(this.OnBeginGetClientMachineName);
            }
            if ((this.onEndGetClientMachineNameDelegate == null)) {
                this.onEndGetClientMachineNameDelegate = new EndOperationDelegate(this.OnEndGetClientMachineName);
            }
            if ((this.onGetClientMachineNameCompletedDelegate == null)) {
                this.onGetClientMachineNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetClientMachineNameCompleted);
            }
            base.InvokeAsync(this.onBeginGetClientMachineNameDelegate, null, this.onEndGetClientMachineNameDelegate, this.onGetClientMachineNameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PalashDynamics.Service.UserInforServiceRef.UserInformationSoap.BeginGetCoordinates(PalashDynamics.Service.UserInforServiceRef.GetCoordinatesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCoordinates(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetCoordinates(string strAddress, System.AsyncCallback callback, object asyncState) {
            PalashDynamics.Service.UserInforServiceRef.GetCoordinatesRequest inValue = new PalashDynamics.Service.UserInforServiceRef.GetCoordinatesRequest();
            inValue.Body = new PalashDynamics.Service.UserInforServiceRef.GetCoordinatesRequestBody();
            inValue.Body.strAddress = strAddress;
            return ((PalashDynamics.Service.UserInforServiceRef.UserInformationSoap)(this)).BeginGetCoordinates(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PalashDynamics.Service.UserInforServiceRef.GetCoordinatesResponse PalashDynamics.Service.UserInforServiceRef.UserInformationSoap.EndGetCoordinates(System.IAsyncResult result) {
            return base.Channel.EndGetCoordinates(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetCoordinates(System.IAsyncResult result) {
            PalashDynamics.Service.UserInforServiceRef.GetCoordinatesResponse retVal = ((PalashDynamics.Service.UserInforServiceRef.UserInformationSoap)(this)).EndGetCoordinates(result);
            return retVal.Body.GetCoordinatesResult;
        }
        
        private System.IAsyncResult OnBeginGetCoordinates(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string strAddress = ((string)(inValues[0]));
            return this.BeginGetCoordinates(strAddress, callback, asyncState);
        }
        
        private object[] OnEndGetCoordinates(System.IAsyncResult result) {
            string retVal = this.EndGetCoordinates(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCoordinatesCompleted(object state) {
            if ((this.GetCoordinatesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCoordinatesCompleted(this, new GetCoordinatesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCoordinatesAsync(string strAddress) {
            this.GetCoordinatesAsync(strAddress, null);
        }
        
        public void GetCoordinatesAsync(string strAddress, object userState) {
            if ((this.onBeginGetCoordinatesDelegate == null)) {
                this.onBeginGetCoordinatesDelegate = new BeginOperationDelegate(this.OnBeginGetCoordinates);
            }
            if ((this.onEndGetCoordinatesDelegate == null)) {
                this.onEndGetCoordinatesDelegate = new EndOperationDelegate(this.OnEndGetCoordinates);
            }
            if ((this.onGetCoordinatesCompletedDelegate == null)) {
                this.onGetCoordinatesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCoordinatesCompleted);
            }
            base.InvokeAsync(this.onBeginGetCoordinatesDelegate, new object[] {
                        strAddress}, this.onEndGetCoordinatesDelegate, this.onGetCoordinatesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PalashDynamics.Service.UserInforServiceRef.UserInformationSoap CreateChannel() {
            return new UserInformationSoapClientChannel(this);
        }
        
        private class UserInformationSoapClientChannel : ChannelBase<PalashDynamics.Service.UserInforServiceRef.UserInformationSoap>, PalashDynamics.Service.UserInforServiceRef.UserInformationSoap {
            
            public UserInformationSoapClientChannel(System.ServiceModel.ClientBase<PalashDynamics.Service.UserInforServiceRef.UserInformationSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetClientUserName(PalashDynamics.Service.UserInforServiceRef.GetClientUserNameRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetClientUserName", _args, callback, asyncState);
                return _result;
            }
            
            public PalashDynamics.Service.UserInforServiceRef.GetClientUserNameResponse EndGetClientUserName(System.IAsyncResult result) {
                object[] _args = new object[0];
                PalashDynamics.Service.UserInforServiceRef.GetClientUserNameResponse _result = ((PalashDynamics.Service.UserInforServiceRef.GetClientUserNameResponse)(base.EndInvoke("GetClientUserName", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetClientMachineName(PalashDynamics.Service.UserInforServiceRef.GetClientMachineNameRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetClientMachineName", _args, callback, asyncState);
                return _result;
            }
            
            public PalashDynamics.Service.UserInforServiceRef.GetClientMachineNameResponse EndGetClientMachineName(System.IAsyncResult result) {
                object[] _args = new object[0];
                PalashDynamics.Service.UserInforServiceRef.GetClientMachineNameResponse _result = ((PalashDynamics.Service.UserInforServiceRef.GetClientMachineNameResponse)(base.EndInvoke("GetClientMachineName", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCoordinates(PalashDynamics.Service.UserInforServiceRef.GetCoordinatesRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetCoordinates", _args, callback, asyncState);
                return _result;
            }
            
            public PalashDynamics.Service.UserInforServiceRef.GetCoordinatesResponse EndGetCoordinates(System.IAsyncResult result) {
                object[] _args = new object[0];
                PalashDynamics.Service.UserInforServiceRef.GetCoordinatesResponse _result = ((PalashDynamics.Service.UserInforServiceRef.GetCoordinatesResponse)(base.EndInvoke("GetCoordinates", _args, result)));
                return _result;
            }
        }
    }
}
