using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel;

namespace PalashDynamics.ValueObjects.Administration
{
    public class clsAutoEmailConfigVO : IValueObject, INotifyPropertyChanged
    {

        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;
        private void OnPropertyChanged(string propertyName)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (null != handler)
            {
                handler.Invoke(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        #endregion

        #region IValueObject Members

        public string ToXml()
        {
            throw new NotImplementedException();
        }

        #endregion


        private long _ID;
        public long ID
        {
            get
            {
                return _ID;
            }

            set
            {
                if (value != _ID)
                {
                    _ID = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        
        private bool _AppointmentConfirmation;
        public bool AppointmentConfirmation
        {
            get
            {
                return _AppointmentConfirmation;
            }

            set
            {
                if (value != _AppointmentConfirmation)
                {
                    _AppointmentConfirmation = value;
                    OnPropertyChanged("AppointmentConfirmation");
                }
            }
        }
        
        private bool _AppointmentCancellation;
        public bool AppointmentCancellation
        {
            get
            {
                return _AppointmentCancellation;
            }

            set
            {
                if (value != _AppointmentCancellation)
                {
                    _AppointmentCancellation = value;
                    OnPropertyChanged("AppointmentCancellation");
                }
            }
        }

        private bool _AutogeneratedPassword;
        public bool AutogeneratedPassword
        {
            get
            {
                return _AutogeneratedPassword;
            }

            set
            {
                if (value != _AutogeneratedPassword)
                {
                    _AutogeneratedPassword = value;
                    OnPropertyChanged("AutogeneratedPassword");
                }
            }
        }
        
        private bool _CampInformation;
        public bool CampInformation
        {
            get
            {
                return _CampInformation;
            }

            set
            {
                if (value != _CampInformation)
                {
                    _CampInformation = value;
                    OnPropertyChanged("CampInformation");
                }
            }
        }

        private bool _PatientRegistration;
        public bool PatientRegistration
        {
            get
            {
                return _PatientRegistration;
            }

            set
            {
                if (value != _PatientRegistration)
                {
                    _PatientRegistration = value;
                    OnPropertyChanged("PatReg");
                }
            }
        }

        private bool _PatientVisit;
        public bool PatientVisit
        {
            get
            {
                return _PatientVisit;
            }

            set
            {
                if (value != _PatientVisit)
                {
                    _PatientVisit = value;
                    OnPropertyChanged("PatVisitClosure");
                }
            }
        }

        private bool _PatientLab;
        public bool PatientLab
        {
            get
            {
                return _PatientLab;
            }

            set
            {
                if (value != _PatientLab)
                {
                    _PatientLab = value;
                    OnPropertyChanged("PatLabResult");
                }
            }
        }

        private bool _PatientLoyaltyReg;
        public bool PatientLoyaltyReg
        {
            get
            {
                return _PatientLoyaltyReg;
            }

            set
            {
                if (value != _PatientLoyaltyReg)
                {
                    _PatientLoyaltyReg = value;
                    OnPropertyChanged("PatLoyaltyReg");
                }
            }
        }


        private bool _PatientLoyaltyExpiry;
        public bool PatientLoyaltyExpiry
        {
            get
            {
                return _PatientLoyaltyExpiry;
            }

            set
            {
                if (value != _PatientLoyaltyExpiry)
                {
                    _PatientLoyaltyExpiry = value;
                    OnPropertyChanged("PatLoyaltyExpiry");
                }
            }
        }

        private bool _AppointmentReminder;
        public bool AppointmentReminder
        {
            get
            {
                return _AppointmentReminder;
            }

            set
            {
                if (value != _AppointmentReminder)
                {
                    _AppointmentReminder = value;
                    OnPropertyChanged("ApptReminder");
                }
            }
        }

        private bool _FollowupReminder;
        public bool FollowupReminder
        {
            get
            {
                return _FollowupReminder;
            }

            set
            {
                if (value != _FollowupReminder)
                {
                    _FollowupReminder = value;
                    OnPropertyChanged("Followup");
                }
            }
        }

        private bool _BirthdayWish;
        public bool BirthdayWish
        {
            get
            {
                return _BirthdayWish;
            }

            set
            {
                if (value != _BirthdayWish)
                {
                    _BirthdayWish = value;
                    OnPropertyChanged("Birthday");
                }
            }
        }

        private long _AppConfirmation;
        public long AppConfirmation
        {
            get
            {
                return _AppConfirmation;
            }

            set
            {
                if (value != _AppConfirmation)
                {
                    _AppConfirmation = value;
                    OnPropertyChanged("AppConfirmationId");
                }
            }
        }

        private long _AutoUserPassword;
        public long AutoUserPassword
        {
            get
            {
                return _AutoUserPassword;
            }

            set
            {
                if (value != _AutoUserPassword)
                {
                    _AutoUserPassword = value;
                    OnPropertyChanged("AutoGeneratedPasswordId");
                }
            }
        }

        private long _CampInfo;
        public long CampInfo
        {
            get
            {
                return _CampInfo;
            }

            set
            {
                if (value != _CampInfo)
                {
                    _CampInfo = value;
                    OnPropertyChanged("CampInfoId");
                }
            }
        }

        private long _AppCancellation;
        public long AppCancellation
        {
            get
            {
                return _AppCancellation;
            }

            set
            {
                if (value != _AppCancellation)
                {
                    _AppCancellation = value;
                    OnPropertyChanged("AppCancellationId");
                }
            }
        }

        private long _AppConfirmationSMS;
        public long AppConfirmationSMS
        {
            get
            {
                return _AppConfirmationSMS;
            }

            set
            {
                if (value != _AppConfirmationSMS)
                {
                    _AppConfirmationSMS = value;
                    OnPropertyChanged("AppConfirmationSMSId");
                }
            }
        }

        private long _AutoUserPasswordSMS;
        public long AutoUserPasswordSMS
        {
            get
            {
                return _AutoUserPasswordSMS;
            }

            set
            {
                if (value != _AutoUserPasswordSMS)
                {
                    _AutoUserPasswordSMS = value;
                    OnPropertyChanged("AutoGeneratedPasswordSMSId");
                }
            }
        }

        private long _CampInfoSMS;
        public long CampInfoSMS
        {
            get
            {
                return _CampInfoSMS;
            }

            set
            {
                if (value != _CampInfoSMS)
                {
                    _CampInfoSMS = value;
                    OnPropertyChanged("CampInfoId");
                }
            }
        }

        private long _AppCancellationSMS;
        public long AppCancellationSMS
        {
            get
            {
                return _AppCancellationSMS;
            }

            set
            {
                if (value != _AppCancellationSMS)
                {
                    _AppCancellationSMS = value;
                    OnPropertyChanged("AppCancellationId");
                }
            }
        }

        //

        private long _PatReg;
        public long PatReg
        {
            get
            {
                return _PatReg;
            }

            set
            {
                if (value != _PatReg)
                {
                    _PatReg = value;
                    OnPropertyChanged("PatRegId");
                }
            }
        }

        private long _PatVisitClose;
        public long PatVisitClose
        {
            get
            {
                return _PatVisitClose;
            }

            set
            {
                if (value != _PatVisitClose)
                {
                    _PatVisitClose = value;
                    OnPropertyChanged("PatVisitClosureId");
                }
            }
        }

        private long _PatLabResult;
        public long PatLabResult
        {
            get
            {
                return _PatLabResult;
            }

            set
            {
                if (value != _PatLabResult)
                {
                    _PatLabResult = value;
                    OnPropertyChanged("PatLabResultId");
                }
            }
        }

        private long _PatLoyaltyCard;
        public long PatLoyaltyCard
        {
            get
            {
                return _PatLoyaltyCard;
            }

            set
            {
                if (value != _PatLoyaltyCard)
                {
                    _PatLoyaltyCard = value;
                    OnPropertyChanged("PatLoyaltyRegId");
                }
            }
        }

        private long _LoyaltyCardExpiry;
        public long LoyaltyCardExpiry
        {
            get
            {
                return _LoyaltyCardExpiry;
            }

            set
            {
                if (value != _LoyaltyCardExpiry)
                {
                    _LoyaltyCardExpiry = value;
                    OnPropertyChanged("PatLoyaltyExpiryId");
                }
            }
        }

        private long _ApptReminder;
        public long ApptReminder
        {
            get
            {
                return _ApptReminder;
            }

            set
            {
                if (value != _ApptReminder)
                {
                    _ApptReminder = value;
                    OnPropertyChanged("ApptReminderId");
                }
            }
        }

        private long _Followup;
        public long Followup
        {
            get
            {
                return _Followup;
            }

            set
            {
                if (value != _Followup)
                {
                    _Followup = value;
                    OnPropertyChanged("FollowupId");
                }
            }
        }

        private long _Birthday;
        public long Birthday
        {
            get
            {
                return _Birthday;
            }

            set
            {
                if (value != _Birthday)
                {
                    _Birthday = value;
                    OnPropertyChanged("BirthdayId");
                }
            }
        }
        //
        private long _PatRegSMS;
        public long PatRegSMS
        {
            get
            {
                return _PatRegSMS;
            }

            set
            {
                if (value != _PatRegSMS)
                {
                    _PatRegSMS = value;
                    OnPropertyChanged("PatRegSMSId");
                }
            }
        }

        private long _PatVisitCloseSMS;
        public long PatVisitCloseSMS
        {
            get
            {
                return _PatVisitCloseSMS;
            }

            set
            {
                if (value != _PatVisitCloseSMS)
                {
                    _PatVisitCloseSMS = value;
                    OnPropertyChanged("PatVisitClosureSMSId");
                }
            }
        }

        private long _PatLabResultSMS;
        public long PatLabResultSMS
        {
            get
            {
                return _PatLabResultSMS;
            }

            set
            {
                if (value != _PatLabResultSMS)
                {
                    _PatLabResultSMS = value;
                    OnPropertyChanged("PatLabResultSMSId");
                }
            }
        }

        private long _PatLoyaltyCardSMS;
        public long PatLoyaltyCardSMS
        {
            get
            {
                return _PatLoyaltyCardSMS;
            }

            set
            {
                if (value != _PatLoyaltyCardSMS)
                {
                    _PatLoyaltyCardSMS = value;
                    OnPropertyChanged("PatLoyaltyRegSMSId");
                }
            }
        }

        private long _LoyaltyCardExpirySMS;
        public long LoyaltyCardExpirySMS
        {
            get
            {
                return _LoyaltyCardExpirySMS;
            }

            set
            {
                if (value != _LoyaltyCardExpirySMS)
                {
                    _LoyaltyCardExpirySMS = value;
                    OnPropertyChanged("PatLoyaltyExpirySMSId");
                }
            }
        }

        private long _ApptReminderSMS;
        public long ApptReminderSMS
        {
            get
            {
                return _ApptReminderSMS;
            }

            set
            {
                if (value != _ApptReminderSMS)
                {
                    _ApptReminderSMS = value;
                    OnPropertyChanged("ApptReminderSMSId");
                }
            }
        }

        private long _FollowupSMS;
        public long FollowupSMS
        {
            get
            {
                return _FollowupSMS;
            }

            set
            {
                if (value != _FollowupSMS)
                {
                    _FollowupSMS = value;
                    OnPropertyChanged("FollowupSMSId");
                }
            }
        }

        private long _BirthdaySMS;
        public long BirthdaySMS
        {
            get
            {
                return _BirthdaySMS;
            }

            set
            {
                if (value != _BirthdaySMS)
                {
                    _BirthdaySMS = value;
                    OnPropertyChanged("BirthdaySMSId");
                }
            }
        }

        // Added By Saily P

        private bool _IsDrugNotify;
        public bool IsDrugNotify
        {
            get
            {
                return _IsDrugNotify;
            }

            set
            {
                if (value != _IsDrugNotify)
                {
                    _IsDrugNotify = value;
                    OnPropertyChanged("IsDrugNotify");
                }
            }
        }

        private bool _IsETNotify;
        public bool IsETNotify
        {
            get
            {
                return _IsETNotify;
            }

            set
            {
                if (value != _IsETNotify)
                {
                    _IsETNotify = value;
                    OnPropertyChanged("IsETNotify");
                }
            }
        }

        private bool _IsOPUNotify;
        public bool IsOPUNotify
        {
            get
            {
                return _IsOPUNotify;
            }

            set
            {
                if (value != _IsOPUNotify)
                {
                    _IsOPUNotify = value;
                    OnPropertyChanged("IsOPUNotify");
                }
            }
        }

        private long _DrugNotify;
        public long DrugNotify
        {
            get
            {
                return _DrugNotify;
            }

            set
            {
                if (value != _DrugNotify)
                {
                    _DrugNotify = value;
                    OnPropertyChanged("DrugNotify");
                }
            }
        }

        private long _ETNotify;
        public long ETNotify
        {
            get
            {
                return _ETNotify;
            }

            set
            {
                if (value != _ETNotify)
                {
                    _ETNotify = value;
                    OnPropertyChanged("ETNotify");
                }
            }
        }

        private long _OPUNotify;
        public long OPUNotify
        {
            get
            {
                return _OPUNotify;
            }

            set
            {
                if (value != _OPUNotify)
                {
                    _OPUNotify = value;
                    OnPropertyChanged("OPUNotify");
                }
            }
        }

        private long _DrugNotifySMS;
        public long DrugNotifySMS
        {
            get
            {
                return _DrugNotifySMS;
            }

            set
            {
                if (value != _DrugNotifySMS)
                {
                    _DrugNotifySMS = value;
                    OnPropertyChanged("DrugNotifySMS");
                }
            }
        }

        private long _ETNotifySMS;
        public long ETNotifySMS
        {
            get
            {
                return _ETNotifySMS;
            }

            set
            {
                if (value != _ETNotifySMS)
                {
                    _ETNotifySMS = value;
                    OnPropertyChanged("ETNotifySMS");
                }
            }
        }

        private long _OPUNotifySMS;
        public long OPUNotifySMS
        {
            get
            {
                return _OPUNotifySMS;
            }

            set
            {
                if (value != _OPUNotifySMS)
                {
                    _OPUNotifySMS = value;
                    OnPropertyChanged("OPUNotifySMS");
                }
            }
        }

    }

    

    public class clsGetAutoEmailConfigBizActionVO : IBizActionValueObject
    {
        #region IBizActionValueObject Members

        public string GetBizAction()
        {
            return "PalashDynamics.BusinessLayer.clsGetAutoEmailConfigBizAction";
        }

        #endregion

        #region IValueObject Members

        public string ToXml()
        {
            return this.ToString();
        }

        #endregion

        private int _SuccessStatus;
        /// <summary>
        /// Output Property.
        /// This property states the outcome of BizAction Process.
        /// </summary>
        public int SuccessStatus
        {
            get { return _SuccessStatus; }
            set { _SuccessStatus = value; }
        }

        private  clsAutoEmailConfigVO objApp = new clsAutoEmailConfigVO();
        /// <summary>
        /// Output Property.
        /// This Property Contains OPDPatient Details Which is Added.
        /// </summary>
        public clsAutoEmailConfigVO Details
        {
            get { return objApp; }
            set { objApp = value; }
        }

    }

    public class clsUpdateAutoEmailConfigBizActionVO : IBizActionValueObject
    {
        #region IBizActionValueObject Members

        public string GetBizAction()
        {
            return "PalashDynamics.BusinessLayer.clsUpdateAutoEmailConfigBizAction";
        }

        #endregion

        #region IValueObject Members

        public string ToXml()
        {
            return this.ToString();
        }

        #endregion


        private int _SuccessStatus;
        /// <summary>
        /// Output Property.
        /// This property states the outcome of BizAction Process.
        /// </summary>
        public int SuccessStatus
        {
            get { return _SuccessStatus; }
            set { _SuccessStatus = value; }
        }

        private clsAutoEmailConfigVO objApp = new clsAutoEmailConfigVO();
        /// <summary>
        /// Output Property.
        /// This Property Contains OPDPatient Details Which is Added.
        /// </summary>
        public clsAutoEmailConfigVO Details
        {
            get { return objApp; }
            set { objApp = value; }
        }


    }
}
