//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.RegisrationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegisrationService.PatientRegistrationSoap")]
    public interface PatientRegistrationSoap {
        
        // CODEGEN: Generating message contract since element name FirstName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveRegistration", ReplyAction="*")]
        WindowsFormsApplication1.RegisrationService.SaveRegistrationResponse SaveRegistration(WindowsFormsApplication1.RegisrationService.SaveRegistrationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveRegistrationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveRegistration", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.RegisrationService.SaveRegistrationRequestBody Body;
        
        public SaveRegistrationRequest() {
        }
        
        public SaveRegistrationRequest(WindowsFormsApplication1.RegisrationService.SaveRegistrationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveRegistrationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long PatientCategoryID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime RegistrationDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MiddleName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string LastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FamilyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public long GenderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public long BloodGroupID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime DateOfBirth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public long MaritalStatusID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public long ReligionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public long OccupationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string CompanyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public long ResiNoCountryCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public long ResiSTDCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string ResidenceNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string MobileNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public long MobileCountryCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string CivilID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string FaxNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string AddressLine1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string AddressLine2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string AddressLine3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string Area;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string City;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string District;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string State;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string Country;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string Pincode;
        
        public SaveRegistrationRequestBody() {
        }
        
        public SaveRegistrationRequestBody(
                    long PatientCategoryID, 
                    System.DateTime RegistrationDate, 
                    string FirstName, 
                    string MiddleName, 
                    string LastName, 
                    string FamilyName, 
                    long GenderID, 
                    long BloodGroupID, 
                    System.DateTime DateOfBirth, 
                    long MaritalStatusID, 
                    long ReligionID, 
                    long OccupationId, 
                    string CompanyName, 
                    long ResiNoCountryCode, 
                    long ResiSTDCode, 
                    string ResidenceNo, 
                    string MobileNo, 
                    long MobileCountryCode, 
                    string CivilID, 
                    string FaxNo, 
                    string Email, 
                    string AddressLine1, 
                    string AddressLine2, 
                    string AddressLine3, 
                    string Area, 
                    string City, 
                    string District, 
                    string State, 
                    string Country, 
                    string Pincode) {
            this.PatientCategoryID = PatientCategoryID;
            this.RegistrationDate = RegistrationDate;
            this.FirstName = FirstName;
            this.MiddleName = MiddleName;
            this.LastName = LastName;
            this.FamilyName = FamilyName;
            this.GenderID = GenderID;
            this.BloodGroupID = BloodGroupID;
            this.DateOfBirth = DateOfBirth;
            this.MaritalStatusID = MaritalStatusID;
            this.ReligionID = ReligionID;
            this.OccupationId = OccupationId;
            this.CompanyName = CompanyName;
            this.ResiNoCountryCode = ResiNoCountryCode;
            this.ResiSTDCode = ResiSTDCode;
            this.ResidenceNo = ResidenceNo;
            this.MobileNo = MobileNo;
            this.MobileCountryCode = MobileCountryCode;
            this.CivilID = CivilID;
            this.FaxNo = FaxNo;
            this.Email = Email;
            this.AddressLine1 = AddressLine1;
            this.AddressLine2 = AddressLine2;
            this.AddressLine3 = AddressLine3;
            this.Area = Area;
            this.City = City;
            this.District = District;
            this.State = State;
            this.Country = Country;
            this.Pincode = Pincode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveRegistrationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveRegistrationResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.RegisrationService.SaveRegistrationResponseBody Body;
        
        public SaveRegistrationResponse() {
        }
        
        public SaveRegistrationResponse(WindowsFormsApplication1.RegisrationService.SaveRegistrationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveRegistrationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaveRegistrationResult;
        
        public SaveRegistrationResponseBody() {
        }
        
        public SaveRegistrationResponseBody(string SaveRegistrationResult) {
            this.SaveRegistrationResult = SaveRegistrationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PatientRegistrationSoapChannel : WindowsFormsApplication1.RegisrationService.PatientRegistrationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatientRegistrationSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.RegisrationService.PatientRegistrationSoap>, WindowsFormsApplication1.RegisrationService.PatientRegistrationSoap {
        
        public PatientRegistrationSoapClient() {
        }
        
        public PatientRegistrationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatientRegistrationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientRegistrationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientRegistrationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.RegisrationService.SaveRegistrationResponse WindowsFormsApplication1.RegisrationService.PatientRegistrationSoap.SaveRegistration(WindowsFormsApplication1.RegisrationService.SaveRegistrationRequest request) {
            return base.Channel.SaveRegistration(request);
        }
        
        public string SaveRegistration(
                    long PatientCategoryID, 
                    System.DateTime RegistrationDate, 
                    string FirstName, 
                    string MiddleName, 
                    string LastName, 
                    string FamilyName, 
                    long GenderID, 
                    long BloodGroupID, 
                    System.DateTime DateOfBirth, 
                    long MaritalStatusID, 
                    long ReligionID, 
                    long OccupationId, 
                    string CompanyName, 
                    long ResiNoCountryCode, 
                    long ResiSTDCode, 
                    string ResidenceNo, 
                    string MobileNo, 
                    long MobileCountryCode, 
                    string CivilID, 
                    string FaxNo, 
                    string Email, 
                    string AddressLine1, 
                    string AddressLine2, 
                    string AddressLine3, 
                    string Area, 
                    string City, 
                    string District, 
                    string State, 
                    string Country, 
                    string Pincode) {
            WindowsFormsApplication1.RegisrationService.SaveRegistrationRequest inValue = new WindowsFormsApplication1.RegisrationService.SaveRegistrationRequest();
            inValue.Body = new WindowsFormsApplication1.RegisrationService.SaveRegistrationRequestBody();
            inValue.Body.PatientCategoryID = PatientCategoryID;
            inValue.Body.RegistrationDate = RegistrationDate;
            inValue.Body.FirstName = FirstName;
            inValue.Body.MiddleName = MiddleName;
            inValue.Body.LastName = LastName;
            inValue.Body.FamilyName = FamilyName;
            inValue.Body.GenderID = GenderID;
            inValue.Body.BloodGroupID = BloodGroupID;
            inValue.Body.DateOfBirth = DateOfBirth;
            inValue.Body.MaritalStatusID = MaritalStatusID;
            inValue.Body.ReligionID = ReligionID;
            inValue.Body.OccupationId = OccupationId;
            inValue.Body.CompanyName = CompanyName;
            inValue.Body.ResiNoCountryCode = ResiNoCountryCode;
            inValue.Body.ResiSTDCode = ResiSTDCode;
            inValue.Body.ResidenceNo = ResidenceNo;
            inValue.Body.MobileNo = MobileNo;
            inValue.Body.MobileCountryCode = MobileCountryCode;
            inValue.Body.CivilID = CivilID;
            inValue.Body.FaxNo = FaxNo;
            inValue.Body.Email = Email;
            inValue.Body.AddressLine1 = AddressLine1;
            inValue.Body.AddressLine2 = AddressLine2;
            inValue.Body.AddressLine3 = AddressLine3;
            inValue.Body.Area = Area;
            inValue.Body.City = City;
            inValue.Body.District = District;
            inValue.Body.State = State;
            inValue.Body.Country = Country;
            inValue.Body.Pincode = Pincode;
            WindowsFormsApplication1.RegisrationService.SaveRegistrationResponse retVal = ((WindowsFormsApplication1.RegisrationService.PatientRegistrationSoap)(this)).SaveRegistration(inValue);
            return retVal.Body.SaveRegistrationResult;
        }
    }
}
